### ISSUE TITLE
error crashing server

### ISSUE THREAD

**Issue by dmccarthy-dev** [OPENi-ict/auth-api#2]
clients
{ [Error: Invalid token: no header in signature 'yJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJuX2VkZTA0OGQyLWM1ZWQtNGQ3NC05ZTBhLWU2MTdlMTE3OTEzNCIsImlzcyI6Imh0dHBzOi8vZGVtbzIub3BlbmktaWN0LmV1L2F1dGgvdG9rZW4iLCJzdWIiOiJuIiwiZXhwIjoxNDI1NzEyMjg3LCJpYXQiOjE0MjU2NjkwODcsIm5vbmNlIjoiYzA2ZDFlZTQtMTMzNi00NmQ4LWFkNDAtOGZkOGE4YjYwODBkIiwidXNlcl9pZCI6Im4iLCJjbG91ZGxldCI6ImNfMTk0ZTk1OTM2MzVkZjVmNjMxNDFjMjQ5M2NkMWFjOTciLCJzY29wZSI6Im9wZW5pIiwib3BlbmktdG9rZW4tdHlwZSI6InNlc3Npb24iLCJyZXNwb25zZV90eXBlIjoiaWRfdG9rZW4ifQ.aLXVFPf0BNsx7NI6eRrpSNN_NPLT1Y8ZxJO2E_VThzmNrkrW6BQ5pch_6IVrjmpTu2brkGYb7vRZoduRzPgL6A']
  code: 'MISSING_HEADER',
  signature: 'yJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJuX2VkZTA0OGQyLWM1ZWQtNGQ3NC05ZTBhLWU2MTdlMTE3OTEzNCIsImlzcyI6Imh0dHBzOi8vZGVtbzIub3BlbmktaWN0LmV1L2F1dGgvdG9rZW4iLCJzdWIiOiJuIiwiZXhwIjoxNDI1NzEyMjg3LCJpYXQiOjE0MjU2NjkwODcsIm5vbmNlIjoiYzA2ZDFlZTQtMTMzNi00NmQ4LWFkNDAtOGZkOGE4YjYwODBkIiwidXNlcl9pZCI6Im4iLCJjbG91ZGxldCI6ImNfMTk0ZTk1OTM2MzVkZjVmNjMxNDFjMjQ5M2NkMWFjOTciLCJzY29wZSI6Im9wZW5pIiwib3BlbmktdG9rZW4tdHlwZSI6InNlc3Npb24iLCJyZXNwb25zZV90eXBlIjoiaWRfdG9rZW4ifQ.aLXVFPf0BNsx7NI6eRrpSNN_NPLT1Y8ZxJO2E_VThzmNrkrW6BQ5pch_6IVrjmpTu2brkGYb7vRZoduRzPgL6A' }
Error: Invalid token: no header in signature 'yJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJuX2VkZTA0OGQyLWM1ZWQtNGQ3NC05ZTBhLWU2MTdlMTE3OTEzNCIsImlzcyI6Imh0dHBzOi8vZGVtbzIub3BlbmktaWN0LmV1L2F1dGgvdG9rZW4iLCJzdWIiOiJuIiwiZXhwIjoxNDI1NzEyMjg3LCJpYXQiOjE0MjU2NjkwODcsIm5vbmNlIjoiYzA2ZDFlZTQtMTMzNi00NmQ4LWFkNDAtOGZkOGE4YjYwODBkIiwidXNlcl9pZCI6Im4iLCJjbG91ZGxldCI6ImNfMTk0ZTk1OTM2MzVkZjVmNjMxNDFjMjQ5M2NkMWFjOTciLCJzY29wZSI6Im9wZW5pIiwib3BlbmktdG9rZW4tdHlwZSI6InNlc3Npb24iLCJyZXNwb25zZV90eXBlIjoiaWRfdG9rZW4ifQ.aLXVFPf0BNsx7NI6eRrpSNN_NPLT1Y8ZxJO2E_VThzmNrkrW6BQ5pch_6IVrjmpTu2brkGYb7vRZoduRzPgL6A'
    at algoFromJWS (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/jsonwebtoken/node_modules/jws/index.js:62:11)
    at Object.jwsVerify [as verify](/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/jsonwebtoken/node_modules/jws/index.js:99:20)
    at Object.module.exports.verify (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/jsonwebtoken/index.js:92:17)
    at processClientsAction (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/lib/mongrel2MsgHandler.js:229:26)
    at /home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/lib/mongrel2MsgHandler.js:387:10
    at callbackWithFilter (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/m2nodehandler/lib/m2nodehandler.js:373:13)
    at Socket.<anonymous> (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/m2nodehandler/lib/m2nodehandler.js:390:23)
    at Socket.emit (events.js:95:17)
    at Object._onImmediate (/home/ubuntu/repos/cloudlet-platform/node_modules/auth_api/node_modules/m2nodehandler/node_modules/zmq/lib/index.js:358:25)
    at processImmediate [as _immediateCallback](timers.js:354:15)

**Comment by dmccarthy-dev** [comment]
Created a separate function that verifies jwt in isolation. It catches the error so that the server doesn't crash and returns an error message to the user.
